[package]
name = "arc-reactor"
version = "0.1.3"
authors = ["seunlanlege <seunlanlege@gmail.com>"]
license ="MIT"
repository = "https://github.com/seunlanlege/arc-reactor"
readme = "README.md"
documentation="https://docs.rs/arc-reactor/~0.1"
description = "Minimal, Asynchronous, Web Framework"
keywords = ["web", "framework", "asynchronous", "futures", "http"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
impl-service = { path = "./impl-service", version="0.1" }
tokio-core = "0.1"
serde_qs = "0.4"
futures-await = { git = "https://github.com/ngg/futures-await", branch = "0.1", version = "0.1" }
hyper = "0.11"
num_cpus = "1.6.2"
route-recognizer = "0.1.12"
anymap = "0.12.1"
serde_json = "1.0"
serde = "1.0"
percent-encoding = "1.0.1"