[package]
name = "arc-reactor"
version = "0.1.0"
authors = ["seunlanlege <seunlanlege@gmail.com>"]
license-file ="./LICENSE"
description = "Minimal, Asynchronous, Web Framework"
keywords = ["web", "framework", "asynchronous", "futures", "http"]
categories = ["web-programming::http-server", "web-programming"]

[dependencies]
impl-service = { path = "./impl-service", version="0.1" }
tokio-core = "0.1"
futures-await = "0.1"
hyper = "0.11"
num_cpus = "1.6.2"
route-recognizer = "0.1.12"
anymap = "0.12.1"
serde_json = "1.0"
serde = "1.0"
url = "1"
regex = "0.1"
lazy_static = "0.2"
