[package]
name = "async-server"
version = "0.1.0"
authors = ["seunlanlege <seunlanlege@gmail.com>"]

[dependencies]
impl-service = { path = "impl-service" }
tokio-io = "*"
tokio-core = "*"
tokio-proto = "*"
tokio-service = "*"
futures = "*"
hyper = "0.11"
net2 = "*"
route-recognizer = "0.1.12"
futures-await = { git = 'https://github.com/alexcrichton/futures-await' }