[package]
name = "simple"
version = "0.1.0"
authors = ["Seun LanLege <seunlanlege@gmail.com>"]

[dependencies]
arc-reactor = { path="../../", version="*", features =["unstable"] }
tokio="0.1"
futures-await="0.1"