[package]
name = "impl-service"
version = "0.1.0"
authors = ["seunlanlege <slanlege@c2gconsulting.com>"]

[dependencies]
quote = { git = 'https://github.com/dtolnay/quote' }
proc-macro2 = { version = "*", features = ["unstable"] }


[lib]
proc-macro = true

[dependencies.syn]
git = 'https://github.com/dtolnay/syn'
features = ["full", "fold", "parsing", "printing", "extra-traits"]
default-features = false